### ISSUE TITLE
缺少文件teacher.pth

### ISSUE THREAD

**Issue by ResTianTian** [Ricardokevins/Kevinpro-NLP-demo#1]
缺少文件报错FileNotFoundError: [Errno 2] No such file or directory: './teacher.pth'
请问这个文件是需要我自己生成吗
刚刚接触nlp有关内容，不是特别熟悉，希望大佬能细心解答

**Comment by Ricardokevins** [comment]
你是单纯的做句子分类嘛，因为我在句子分类里集成了对抗学习和知识蒸馏的代码，所以有一点点的问题，你遇到的这个问题就是知识蒸馏里teachermodel的缺失

如果你只是做句子分类，我稍后会更新代码，修复这个问题

**Comment by Ricardokevins** [comment]
> 缺少文件报错FileNotFoundError: [Errno 2] No such file or directory: './teacher.pth'
> 请问这个文件是需要我自己生成吗
> 刚刚接触nlp有关内容，不是特别熟悉，希望大佬能细心解答

你是单纯的做句子分类嘛，因为我在句子分类里集成了对抗学习和知识蒸馏的代码，所以有一点点的问题，你遇到的这个问题就是知识蒸馏里teachermodel的缺失

如果你只是做句子分类，我稍后会更新代码，修复这个问题

**Comment by ResTianTian** [comment]
我目前主要想学习您的对抗学习的代码思想，想先运行起来看看，非常感谢

**Comment by Ricardokevins** [comment]
> 我目前主要想学习您的对抗学习的代码思想，想先运行起来看看，非常感谢

已经更新了，我本地试运行没有遇到问题，你可以试试

**Comment by ResTianTian** [comment]
>> 已经更新了，我本地试运行没有遇到问题，你可以试试
好的，再次感谢

**Comment by Ricardokevins** [comment]
> > > 已经更新了，我本地试运行没有遇到问题，你可以试试
> > > 好的，再次感谢

没事
