### ISSUE TITLE
Pointer Generator

### ISSUE THREAD

**Issue by YUECHE77** [Ricardokevins/Kevinpro-NLP-demo#17]
你好，

作者的pointer generator部分的代码能跑起来嘛？我最近也在做这方面的内容，代码写好了，但是模型训练出来得到的效果很差很差。

希望得到您的回复。

谢谢。

**Comment by Ricardokevins** [comment]
> 你好，
> 
> 作者的pointer generator部分的代码能跑起来嘛？我最近也在做这方面的内容，代码写好了，但是模型训练出来得到的效果很差很差。
> 
> 希望得到您的回复。
> 
> 谢谢。

远古代码了，我当时应该是能用的，但是你要说现在过了这么久能不能用我就不确定了hhh

**Comment by YUECHE77** [comment]
感谢回复！

那作者还记得当时跑出来的模型效果如何吗？是好是坏呢？

以及，如果方便的话，能麻烦您提供一下当时的数据集吗？我知道您使用的是微博的那个数据集，但是这个数据集不知道为啥，全网都找不到了 ... ... 所有分享的连接都显示“危险文件”字样，根本打不开 ... ...

如果找不到当时的数据集了也没有关系，我自己再研究研究就是了。

再次感谢。

**Comment by Ricardokevins** [comment]
> 感谢回复！
> 
> 那作者还记得当时跑出来的模型效果如何吗？是好是坏呢？
> 
> 以及，如果方便的话，能麻烦您提供一下当时的数据集吗？我知道您使用的是微博的那个数据集，但是这个数据集不知道为啥，全网都找不到了 ... ... 所有分享的连接都显示“危险文件”字样，根本打不开 ... ...
> 
> 如果找不到当时的数据集了也没有关系，我自己再研究研究就是了。
> 
> 再次感谢。

记不清了，这都好多年了。后续有BART等模型效果不错，更不用说现在的LLM了，你可以考虑其他的数据集

**Comment by YUECHE77** [comment]
好的谢谢。基于BART的摘要生成模型我已经训练出来了，效果确实很不错，rouge_1能到0.37左右。主要是pointer generator我觉得真的很有意思，想复现出来。我自己再去研究研究。
